spring.application.name=anomalog
spring.jackson.mapper.accept-case-insensitive-enums=true
log.source.path=app.log
log.source.polling-interval-ms=200
log.source.start-from-end=true
anomaly.detection.window-size=5
anomaly.detection.history-size=100
anomaly.detection.spike-threshold=3.0